# Name of the GitHub Action
name: Deploy New APK and Update JSON

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Clean up old APKs
        run: find downloads -type f -name "*.apk" -delete

      # --- MODIFIED STEP ---
      # Now it downloads ANY .apk file from your release, not just one with a specific name.
      - name: Download release asset (*.apk)
        uses: robinraju/release-downloader@v1.9
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          fileName: "*.apk" # <-- This now uses a wildcard to find any .apk
          target: "downloads/"
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- MODIFIED STEP ---
      # Now it renames ANY .apk file it finds in the folder.
      - name: Rename APK with version tag
        run: |
          # Find the downloaded .apk file (there should only be one) and rename it.
          mv downloads/*.apk downloads/app-release-${{ github.ref_name }}.apk
          echo "Renamed APK to app-release-${{ github.ref_name }}.apk"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update apk-info.json and version-check.json
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
          GITHUB_REPO: ${{ github.repository }}
          NEW_APK_FILENAME: "app-release-${{ github.ref_name }}.apk"
        run: |
          const fs = require('fs');
          const newApkFilename = process.env.NEW_APK_FILENAME;
          const apkInfoPath = './apk-info.json';
          const apkPath = `./downloads/${newApkFilename}`;
          const stats = fs.statSync(apkPath);
          const fileSizeInMB = (stats.size / (1024 * 1024)).toFixed(1);
          const versionName = "${{ github.ref_name }}".replace('v', '');
          const today = new Date().toISOString().slice(0, 10);
          const webInfo = {
            version: versionName,
            update_date: today,
            size: `${fileSizeInMB} MB`,
            apk_url: `./downloads/${newApkFilename}`
          };
          fs.writeFileSync(apkInfoPath, JSON.stringify(webInfo, null, 2));
          console.log(`Updated ${apkInfoPath} with new APK URL: ${webInfo.apk_url}`);
          const appCheckPath = './version-check.json';
          const versionParts = versionName.split('.').map(part => parseInt(part, 10));
          const generatedVersionCode = (versionParts[0] * 10000) + (versionParts[1] * 100) + (versionParts[2] || 0);
          const releaseNotes = process.env.RELEASE_NOTES || "General improvements and bug fixes.";
          const downloadUrl = `https://raw.githubusercontent.com/${process.env.GITHUB_REPO}/main/downloads/${newApkFilename}`;
          const appCheckInfo = {
            versionCode: generatedVersionCode,
            versionName: versionName,
            downloadUrl: downloadUrl,
            whatsNew: releaseNotes
          };
          fs.writeFileSync(appCheckPath, JSON.stringify(appCheckInfo, null, 4));
          console.log(`Generated ${appCheckPath} with versionCode ${generatedVersionCode} and URL: ${downloadUrl}`);
        shell: node {0}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): Auto-update APK and JSON for version ${{ github.ref_name }}"
          file_pattern: "downloads/*.apk apk-info.json version-check.json"
